"""Make Member.socials not null

Revision ID: 0422a147fab6
Revises: 46cef8277b5e
Create Date: 2024-11-23 02:44:38.996931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0422a147fab6'
down_revision: Union[str, None] = '46cef8277b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'socials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default='{}')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'socials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
