"""Add more fields to Member

Revision ID: 46cef8277b5e
Revises: c3d8b72f95c9
Create Date: 2024-11-23 02:30:01.900597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46cef8277b5e'
down_revision: Union[str, None] = 'c3d8b72f95c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('telegram', sa.String(), nullable=True))
    op.add_column('members', sa.Column('socials', sa.JSON(), nullable=True))
    op.add_column('members', sa.Column('repertoire', sa.String(), server_default='', nullable=False))
    op.add_column('members', sa.Column('band_structure', sa.String(), server_default='', nullable=False))
    op.add_column('members', sa.Column('notes', sa.String(), server_default='', nullable=False))
    op.alter_column('members', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'retired', name='status_enum'),
               nullable=False)
    op.drop_column('members', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('contacts', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('members', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'retired', name='status_enum'),
               nullable=True)
    op.drop_column('members', 'notes')
    op.drop_column('members', 'band_structure')
    op.drop_column('members', 'repertoire')
    op.drop_column('members', 'socials')
    op.drop_column('members', 'telegram')
    # ### end Alembic commands ###
