"""Add indexes for relations

Revision ID: c3d8b72f95c9
Revises: 85e20e7326a3
Create Date: 2024-11-19 04:57:51.335975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d8b72f95c9'
down_revision: Union[str, None] = '85e20e7326a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_member_instrument_relation_instruments_id'), 'member_instrument_relation', ['instruments_id'], unique=False)
    op.create_index(op.f('ix_member_instrument_relation_member_id'), 'member_instrument_relation', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_specialisation_relation_member_id'), 'member_specialisation_relation', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_specialisation_relation_spec_id'), 'member_specialisation_relation', ['spec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_specialisation_relation_spec_id'), table_name='member_specialisation_relation')
    op.drop_index(op.f('ix_member_specialisation_relation_member_id'), table_name='member_specialisation_relation')
    op.drop_index(op.f('ix_member_instrument_relation_member_id'), table_name='member_instrument_relation')
    op.drop_index(op.f('ix_member_instrument_relation_instruments_id'), table_name='member_instrument_relation')
    # ### end Alembic commands ###
